-- saas_jardines_dev.countries definition

CREATE TABLE `countries` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `code` varchar(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_b47cbb5311bad9c9ae17b8c1ed` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.permissions definition

CREATE TABLE `permissions` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `resource` varchar(100) NOT NULL,
  `action` varchar(50) NOT NULL,
  `description` text NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_48ce552495d14eae9b187bb671` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.subscription_plans definition

CREATE TABLE `subscription_plans` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `code` varchar(50) NOT NULL,
  `max_students` int NOT NULL,
  `max_users` int NOT NULL,
  `monthly_price` decimal(10,2) NOT NULL,
  `is_active` tinyint NOT NULL DEFAULT '1',
  `description` text,
  `features` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_2d2df70a81d37c893ef216caf8` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.regions definition

CREATE TABLE `regions` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `code` varchar(10) DEFAULT NULL,
  `country_id` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_88710f9af21f62e1bf43bbce751` (`country_id`),
  CONSTRAINT `FK_88710f9af21f62e1bf43bbce751` FOREIGN KEY (`country_id`) REFERENCES `countries` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.cities definition

CREATE TABLE `cities` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `code` varchar(10) NOT NULL,
  `latitude` decimal(10,8) DEFAULT NULL,
  `longitude` decimal(10,8) DEFAULT NULL,
  `region_id` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_42a294591feef6af3d96d60132a` (`region_id`),
  CONSTRAINT `FK_42a294591feef6af3d96d60132a` FOREIGN KEY (`region_id`) REFERENCES `regions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.companies definition

CREATE TABLE `companies` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `legal_name` varchar(255) NOT NULL,
  `rut` varchar(50) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `address` text,
  `city_id` varchar(255) NOT NULL,
  `logo_url` text,
  `is_active` tinyint NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_5d80d8df0f3b64b99fcb916591` (`rut`),
  UNIQUE KEY `IDX_d0af6f5866201d5cb424767744` (`email`),
  KEY `FK_6398f263de442e9becb2b7b68d3` (`city_id`),
  CONSTRAINT `FK_6398f263de442e9becb2b7b68d3` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.company_subscriptions definition

CREATE TABLE `company_subscriptions` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `company_id` varchar(255) NOT NULL,
  `subscription_plan_id` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL,
  `start_date` datetime NOT NULL,
  `end_date` datetime NOT NULL,
  `auto_renew` tinyint DEFAULT '1',
  `cancelled_at` datetime DEFAULT NULL,
  `cancelled_reason` text,
  PRIMARY KEY (`id`),
  KEY `FK_0aa4c0ffc36ddb76fee4e05ea4b` (`company_id`),
  KEY `FK_bfc2f6f171e53a43a0acf16ef67` (`subscription_plan_id`),
  CONSTRAINT `FK_0aa4c0ffc36ddb76fee4e05ea4b` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `FK_bfc2f6f171e53a43a0acf16ef67` FOREIGN KEY (`subscription_plan_id`) REFERENCES `subscription_plans` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.levels definition

CREATE TABLE `levels` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `company_id` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `code` varchar(50) NOT NULL,
  `description` text NOT NULL,
  `min_age_months` int NOT NULL,
  `max_age_months` int NOT NULL,
  `capacity` int NOT NULL,
  `academic_year` varchar(10) NOT NULL,
  `is_active` tinyint NOT NULL DEFAULT '1',
  `display_order` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `FK_6b00e7a6b28367129e0f7104319` (`company_id`),
  CONSTRAINT `FK_6b00e7a6b28367129e0f7104319` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.roles definition

CREATE TABLE `roles` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `company_id` varchar(255) NOT NULL,
  `name` varchar(100) NOT NULL,
  `code` varchar(50) NOT NULL,
  `description` text NOT NULL,
  `is_system_role` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `FK_4bc1204a05dde26383e3955b0a1` (`company_id`),
  CONSTRAINT `FK_4bc1204a05dde26383e3955b0a1` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.users definition

CREATE TABLE `users` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `company_id` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `first_name` varchar(255) NOT NULL,
  `last_name` varchar(255) NOT NULL,
  `rut` varchar(50) NOT NULL,
  `phone` varchar(50) NOT NULL,
  `avatar_url` text,
  `is_active` tinyint NOT NULL DEFAULT '1',
  `email_verified` tinyint NOT NULL DEFAULT '0',
  `last_login_at` timestamp NULL DEFAULT NULL,
  `password_reset_token` varchar(255) DEFAULT NULL,
  `password_reset_expires` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_97672ac88f789774dd47f7c8be` (`email`),
  KEY `FK_7ae6334059289559722437bcc1c` (`company_id`),
  CONSTRAINT `FK_7ae6334059289559722437bcc1c` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.vehicles definition

CREATE TABLE `vehicles` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `company_id` varchar(255) NOT NULL,
  `license_plate` varchar(50) NOT NULL,
  `internal_code` varchar(50) DEFAULT NULL,
  `brand` varchar(100) NOT NULL,
  `model` varchar(100) NOT NULL,
  `year` int NOT NULL,
  `color` varchar(50) NOT NULL,
  `vin` varchar(100) DEFAULT NULL,
  `capacity` int NOT NULL,
  `capacity_students` int NOT NULL,
  `has_wheelchair_access` tinyint NOT NULL DEFAULT '0',
  `wheelchair_capacity` int DEFAULT NULL,
  `engine_type` varchar(50) DEFAULT NULL,
  `fuel_type` varchar(50) DEFAULT NULL,
  `current_mileage` int DEFAULT NULL,
  `last_mileage_update` date DEFAULT NULL,
  `insurance_company` varchar(255) NOT NULL,
  `insurance_policy_number` varchar(100) NOT NULL,
  `insurance_type` varchar(100) DEFAULT NULL,
  `insurance_issue_date` date DEFAULT NULL,
  `insurance_expiry_date` date NOT NULL,
  `technical_review_expiry` date NOT NULL,
  `circulation_permit_number` varchar(100) DEFAULT NULL,
  `circulation_permit_expiry` date NOT NULL,
  `has_fire_extinguisher` tinyint NOT NULL DEFAULT '1',
  `fire_extinguisher_expiry` date DEFAULT NULL,
  `has_first_aid_kit` tinyint NOT NULL DEFAULT '1',
  `has_gps_tracker` tinyint NOT NULL DEFAULT '0',
  `gps_device_id` varchar(100) DEFAULT NULL,
  `last_maintenance_date` date DEFAULT NULL,
  `next_maintenance_date` date DEFAULT NULL,
  `maintenance_frequency_km` int DEFAULT NULL,
  `ownership_type` varchar(50) NOT NULL DEFAULT 'owned',
  `owner_name` varchar(255) DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'active',
  `condition` varchar(50) NOT NULL DEFAULT 'good',
  `notes` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_7e9fab2e8625b63613f67bd706` (`license_plate`),
  KEY `FK_e11ef2dcd880132d31bd9f92c2a` (`company_id`),
  CONSTRAINT `FK_e11ef2dcd880132d31bd9f92c2a` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.activity_plannings definition

CREATE TABLE `activity_plannings` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `company_id` varchar(255) NOT NULL,
  `teacher_id` varchar(255) NOT NULL,
  `level_id` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `code` varchar(50) DEFAULT NULL,
  `planning_type` varchar(50) DEFAULT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `academic_year` varchar(10) NOT NULL,
  `objectives` text NOT NULL,
  `core_learning_areas` json NOT NULL,
  `activities` json NOT NULL,
  `resources` text NOT NULL,
  `evaluation_criteria` text NOT NULL,
  `expected_outcomes` text NOT NULL,
  `adaptations` text,
  `student_context` text,
  `status` varchar(50) NOT NULL DEFAULT 'draft',
  `submitted_at` timestamp NULL DEFAULT NULL,
  `submitted_to` varchar(255) DEFAULT NULL,
  `reviewed_by` varchar(255) DEFAULT NULL,
  `reviewed_at` timestamp NULL DEFAULT NULL,
  `approved_by` varchar(255) DEFAULT NULL,
  `approved_at` timestamp NULL DEFAULT NULL,
  `feedback` text,
  `revision_number` int NOT NULL DEFAULT '1',
  `template_id` varchar(255) DEFAULT NULL,
  `is_template` tinyint NOT NULL DEFAULT '0',
  `template_name` varchar(255) DEFAULT NULL,
  `attachments` json DEFAULT NULL,
  `views` int NOT NULL DEFAULT '0',
  `last_viewed_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_ab511558653c93c1acc67cc2ca6` (`company_id`),
  KEY `FK_ab2f044a0d700b7e55e88ecf946` (`teacher_id`),
  KEY `FK_9a15e8f8adc835b85bba458247c` (`level_id`),
  KEY `FK_d021832399eb02b39dcdffb8420` (`submitted_to`),
  KEY `FK_75d5a4725e2292b40e3641f5317` (`reviewed_by`),
  KEY `FK_8df967d906e355078784b301fe7` (`approved_by`),
  KEY `FK_e16bc8881b9453deaed6d2d1814` (`template_id`),
  CONSTRAINT `FK_75d5a4725e2292b40e3641f5317` FOREIGN KEY (`reviewed_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_8df967d906e355078784b301fe7` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_9a15e8f8adc835b85bba458247c` FOREIGN KEY (`level_id`) REFERENCES `levels` (`id`),
  CONSTRAINT `FK_ab2f044a0d700b7e55e88ecf946` FOREIGN KEY (`teacher_id`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_ab511558653c93c1acc67cc2ca6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `FK_d021832399eb02b39dcdffb8420` FOREIGN KEY (`submitted_to`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_e16bc8881b9453deaed6d2d1814` FOREIGN KEY (`template_id`) REFERENCES `activity_plannings` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.class_book_entries definition

CREATE TABLE `class_book_entries` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `company_id` varchar(255) NOT NULL,
  `teacher_id` varchar(255) NOT NULL,
  `level_id` varchar(255) NOT NULL,
  `date` date NOT NULL,
  `entry_number` varchar(50) DEFAULT NULL,
  `academic_year` varchar(10) NOT NULL,
  `total_students` int NOT NULL,
  `students_present` int NOT NULL,
  `students_absent` int NOT NULL,
  `students_late` int NOT NULL,
  `attendance_percentage` decimal(5,2) NOT NULL,
  `activities_performed` text NOT NULL,
  `core_learning_areas` json DEFAULT NULL,
  `resources_used` text NOT NULL,
  `teaching_methodology` varchar(100) DEFAULT NULL,
  `learning_environment` text,
  `general_observations` text,
  `achievements` text,
  `challenges` text,
  `incidents` text,
  `special_activities` text,
  `family_communications` text,
  `photos` json DEFAULT NULL,
  `documents` json DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'draft',
  `is_locked` tinyint NOT NULL DEFAULT '0',
  `locked_at` timestamp NULL DEFAULT NULL,
  `locked_by` varchar(255) DEFAULT NULL,
  `reviewed_by` varchar(255) DEFAULT NULL,
  `reviewed_at` timestamp NULL DEFAULT NULL,
  `review_notes` text,
  PRIMARY KEY (`id`),
  KEY `FK_1e5b7a96ad0046eea4efaf77c17` (`company_id`),
  KEY `FK_c844aee2b3f77c463d063afe15c` (`teacher_id`),
  KEY `FK_470b9da03f4a483ac89c4a01c61` (`level_id`),
  KEY `FK_4ec67e62c6b75b02aa6e5c14376` (`locked_by`),
  KEY `FK_68cf49e75f55d53e031ac8ccb3e` (`reviewed_by`),
  CONSTRAINT `FK_1e5b7a96ad0046eea4efaf77c17` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `FK_470b9da03f4a483ac89c4a01c61` FOREIGN KEY (`level_id`) REFERENCES `levels` (`id`),
  CONSTRAINT `FK_4ec67e62c6b75b02aa6e5c14376` FOREIGN KEY (`locked_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_68cf49e75f55d53e031ac8ccb3e` FOREIGN KEY (`reviewed_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_c844aee2b3f77c463d063afe15c` FOREIGN KEY (`teacher_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.drivers definition

CREATE TABLE `drivers` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `company_id` varchar(255) NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `first_name` varchar(255) NOT NULL,
  `last_name` varchar(255) NOT NULL,
  `rut` varchar(50) NOT NULL,
  `birth_date` date NOT NULL,
  `phone` varchar(50) NOT NULL,
  `phone_secondary` varchar(50) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `address` text NOT NULL,
  `city_id` varchar(255) DEFAULT NULL,
  `emergencyContactName` varchar(255) NOT NULL,
  `emergency_contact_relationship` varchar(100) NOT NULL,
  `emergency_contact_phone` varchar(50) NOT NULL,
  `emergency_contact_phone_secondary` varchar(50) DEFAULT NULL,
  `license_number` varchar(100) NOT NULL,
  `license_type` varchar(50) NOT NULL,
  `license_issue_date` date NOT NULL,
  `license_expiration_date` date NOT NULL,
  `license_restriction` text,
  `years_of_experience` int NOT NULL,
  `previous_experience` text,
  `last_medical_exam_date` date DEFAULT NULL,
  `next_medical_exam_date` date DEFAULT NULL,
  `medical_restriction` text,
  `status` varchar(50) NOT NULL,
  `suspension_reason` text,
  `suspension_start_date` date DEFAULT NULL,
  `suspension_end_date` date DEFAULT NULL,
  `hire_date` date NOT NULL,
  `termination_date` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_2ffd7a9646568f60a28f25c5912` (`company_id`),
  KEY `FK_8e224f1b8f05ace7cfc7c76d03b` (`user_id`),
  KEY `FK_049be208a520d774555b6f25771` (`city_id`),
  CONSTRAINT `FK_049be208a520d774555b6f25771` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`),
  CONSTRAINT `FK_2ffd7a9646568f60a28f25c5912` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `FK_8e224f1b8f05ace7cfc7c76d03b` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.guardians definition

CREATE TABLE `guardians` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `company_id` varchar(255) NOT NULL,
  `user_id` varchar(255) DEFAULT NULL,
  `first_name` varchar(255) NOT NULL,
  `last_name` varchar(255) NOT NULL,
  `rut` varchar(50) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(50) NOT NULL,
  `phone_secondary` varchar(50) DEFAULT NULL,
  `relationship` varchar(100) NOT NULL,
  `address` text NOT NULL,
  `city_id` varchar(255) DEFAULT NULL,
  `occupation` varchar(255) DEFAULT NULL,
  `workplace` varchar(255) DEFAULT NULL,
  `work_phone` varchar(50) DEFAULT NULL,
  `preferred_contact_method` varchar(50) NOT NULL DEFAULT 'email',
  `contact_time_preference` varchar(100) DEFAULT NULL,
  `is_primary` tinyint NOT NULL DEFAULT '0',
  `is_authorized_pickup` tinyint NOT NULL DEFAULT '1',
  `is_emergency_contact` tinyint NOT NULL DEFAULT '1',
  `is_authorized_medical_decisions` tinyint NOT NULL DEFAULT '0',
  `invitation_token` varchar(255) DEFAULT NULL,
  `invitation_sent_at` timestamp NULL DEFAULT NULL,
  `invitation_accepted_at` timestamp NULL DEFAULT NULL,
  `invitation_expires_at` timestamp NULL DEFAULT NULL,
  `data_consent_given` tinyint NOT NULL DEFAULT '0',
  `data_consent_date` timestamp NULL DEFAULT NULL,
  `deleted_by` varchar(255) DEFAULT NULL,
  `photo_consent` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `FK_2f2efae2168b0b6da9c8f9ba5e6` (`company_id`),
  KEY `FK_f1d05a3a2d70db0a25479b67189` (`user_id`),
  KEY `FK_c2157ca457d7bc2bc484c986212` (`city_id`),
  KEY `FK_9f6636005d9646894e394461941` (`deleted_by`),
  CONSTRAINT `FK_2f2efae2168b0b6da9c8f9ba5e6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `FK_9f6636005d9646894e394461941` FOREIGN KEY (`deleted_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_c2157ca457d7bc2bc484c986212` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`),
  CONSTRAINT `FK_f1d05a3a2d70db0a25479b67189` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.planning_reviews definition

CREATE TABLE `planning_reviews` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `planning_id` varchar(255) NOT NULL,
  `reviewer_id` varchar(255) NOT NULL,
  `action` varchar(50) NOT NULL,
  `feedback` text,
  `checklist_items` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_237c16df4e3e3063b6918d97f9d` (`planning_id`),
  KEY `FK_b3fda67b119272cba98269733c1` (`reviewer_id`),
  CONSTRAINT `FK_237c16df4e3e3063b6918d97f9d` FOREIGN KEY (`planning_id`) REFERENCES `activity_plannings` (`id`),
  CONSTRAINT `FK_b3fda67b119272cba98269733c1` FOREIGN KEY (`reviewer_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.role_permissions definition

CREATE TABLE `role_permissions` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `role_id` varchar(255) NOT NULL,
  `company_id` varchar(255) NOT NULL,
  `permission_id` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_178199805b901ccd220ab7740ec` (`role_id`),
  KEY `FK_d6252ee42a4cb1cee588d10ac7f` (`company_id`),
  KEY `FK_17022daf3f885f7d35423e9971e` (`permission_id`),
  CONSTRAINT `FK_17022daf3f885f7d35423e9971e` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`),
  CONSTRAINT `FK_178199805b901ccd220ab7740ec` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`),
  CONSTRAINT `FK_d6252ee42a4cb1cee588d10ac7f` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.routes definition

CREATE TABLE `routes` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `company_id` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `code` varchar(50) DEFAULT NULL,
  `description` text,
  `vehicle_id` varchar(255) NOT NULL,
  `primary_driver_id` varchar(255) NOT NULL,
  `backup_driver_id` varchar(255) DEFAULT NULL,
  `route_type` varchar(50) NOT NULL,
  `service_type` varchar(50) NOT NULL DEFAULT 'regular',
  `start_location_name` varchar(255) NOT NULL,
  `start_address` text NOT NULL,
  `start_latitude` decimal(10,8) NOT NULL,
  `start_longitude` decimal(11,8) NOT NULL,
  `end_location_name` varchar(255) NOT NULL,
  `end_address` text NOT NULL,
  `end_latitude` decimal(10,8) NOT NULL,
  `end_longitude` decimal(11,8) NOT NULL,
  `scheduled_start_time` time NOT NULL,
  `scheduled_end_time` time NOT NULL,
  `estimated_duration_minutes` int NOT NULL,
  `estimated_distance_km` decimal(8,2) NOT NULL,
  `operating_days` json DEFAULT NULL,
  `date_exceptions` json DEFAULT NULL,
  `max_delay_tolerance_minutes` int NOT NULL DEFAULT '10',
  `notify_guardians_on_start` tinyint NOT NULL DEFAULT '1',
  `notify_guardians_on_approach` tinyint NOT NULL DEFAULT '1',
  `approach_notification_distance_meters` int NOT NULL DEFAULT '500',
  `is_optimized` tinyint NOT NULL DEFAULT '0',
  `last_optimized_at` timestamp NULL DEFAULT NULL,
  `optimization_algorithm` varchar(50) DEFAULT NULL,
  `color` varchar(7) DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'active',
  `is_active` tinyint NOT NULL DEFAULT '1',
  `total_students` int NOT NULL DEFAULT '0',
  `notes` text,
  `created_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_0421b1f004f7cf3063c20a083be` (`company_id`),
  KEY `FK_4799f838f95331185270ea981df` (`vehicle_id`),
  KEY `FK_7034ae96c706e4cb69257aa6b31` (`primary_driver_id`),
  KEY `FK_1769e6f9c4e73aca59877053c47` (`backup_driver_id`),
  KEY `FK_fa078723c3b424cbe5a39b83c9a` (`created_by`),
  CONSTRAINT `FK_0421b1f004f7cf3063c20a083be` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `FK_1769e6f9c4e73aca59877053c47` FOREIGN KEY (`backup_driver_id`) REFERENCES `drivers` (`id`),
  CONSTRAINT `FK_4799f838f95331185270ea981df` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicles` (`id`),
  CONSTRAINT `FK_7034ae96c706e4cb69257aa6b31` FOREIGN KEY (`primary_driver_id`) REFERENCES `drivers` (`id`),
  CONSTRAINT `FK_fa078723c3b424cbe5a39b83c9a` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.students definition

CREATE TABLE `students` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `company_id` varchar(255) NOT NULL,
  `first_name` varchar(255) NOT NULL,
  `last_name` varchar(255) NOT NULL,
  `rut` varchar(50) DEFAULT NULL,
  `birth_date` date NOT NULL,
  `gender` varchar(50) NOT NULL,
  `photo_url` text,
  `address` text NOT NULL,
  `enrollment_date` date NOT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'active',
  `city_id` varchar(255) DEFAULT NULL,
  `level_id` varchar(255) DEFAULT NULL,
  `enrollment_number` varchar(50) DEFAULT NULL,
  `withdrawal_date` date DEFAULT NULL,
  `withdrawal_reason` text,
  `deleted_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_27e62bb071fdd6c06508bf36062` (`company_id`),
  KEY `FK_678c4fcdaf30c07931919c2d422` (`city_id`),
  KEY `FK_ebc3adae3c7b211f927b6403bc5` (`level_id`),
  KEY `FK_eb2f2d82cad299a0b81ed539936` (`deleted_by`),
  CONSTRAINT `FK_27e62bb071fdd6c06508bf36062` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `FK_678c4fcdaf30c07931919c2d422` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`),
  CONSTRAINT `FK_eb2f2d82cad299a0b81ed539936` FOREIGN KEY (`deleted_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_ebc3adae3c7b211f927b6403bc5` FOREIGN KEY (`level_id`) REFERENCES `levels` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.trips definition

CREATE TABLE `trips` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `company_id` varchar(255) NOT NULL,
  `route_id` varchar(255) NOT NULL,
  `driver_id` varchar(255) NOT NULL,
  `vehicle_id` varchar(255) NOT NULL,
  `date` date NOT NULL,
  `trip_type` varchar(50) NOT NULL,
  `trip_number` int NOT NULL DEFAULT '1',
  `scheduled_start_time` time NOT NULL,
  `actual_start_time` time DEFAULT NULL,
  `scheduled_end_time` time DEFAULT NULL,
  `actual_end_time` time DEFAULT NULL,
  `actual_duration_minutes` int DEFAULT NULL,
  `start_latitude` decimal(10,8) DEFAULT NULL,
  `start_longitude` decimal(11,8) DEFAULT NULL,
  `end_latitude` decimal(10,8) DEFAULT NULL,
  `end_longitude` decimal(11,8) DEFAULT NULL,
  `start_mileage` int DEFAULT NULL,
  `end_mileage` int DEFAULT NULL,
  `total_distance_km` decimal(8,2) DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'scheduled',
  `total_students_expected` int NOT NULL,
  `total_students_picked_up` int NOT NULL DEFAULT '0',
  `total_students_dropped_off` int NOT NULL DEFAULT '0',
  `students_absent` int NOT NULL DEFAULT '0',
  `total_stops` int NOT NULL,
  `completed_stops` int NOT NULL DEFAULT '0',
  `skipped_stops` int NOT NULL DEFAULT '0',
  `is_delayed` tinyint NOT NULL DEFAULT '0',
  `delay_minutes` int DEFAULT NULL,
  `delay_reason` text,
  `has_route_deviation` tinyint NOT NULL DEFAULT '0',
  `deviation_reason` text,
  `weather_conditions` varchar(100) DEFAULT NULL,
  `traffic_conditions` varchar(100) DEFAULT NULL,
  `has_incidents` tinyint NOT NULL DEFAULT '0',
  `incident_count` int NOT NULL DEFAULT '0',
  `fuel_level_start` varchar(50) DEFAULT NULL,
  `fuel_level_end` varchar(50) DEFAULT NULL,
  `driver_rating` decimal(3,2) DEFAULT NULL,
  `notes` text,
  `driver_comments` text,
  `cancelled_at` timestamp NULL DEFAULT NULL,
  `cancelled_by` varchar(255) DEFAULT NULL,
  `cancellation_reason` text,
  `start_notification_sent` tinyint NOT NULL DEFAULT '0',
  `start_notification_sent_at` timestamp NULL DEFAULT NULL,
  `completion_notification_sent` tinyint NOT NULL DEFAULT '0',
  `completion_notification_sent_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_ee38d00bcd1ef4a005bab44c0a4` (`company_id`),
  KEY `FK_e49dbbd9991c9b7baec9779e7ce` (`route_id`),
  KEY `FK_44d36110fb38f45c2f15c946ddb` (`driver_id`),
  KEY `FK_ab4b806373c2ee43946679d572e` (`vehicle_id`),
  KEY `FK_00d26d8ee8665d8e4be3b55db81` (`cancelled_by`),
  CONSTRAINT `FK_00d26d8ee8665d8e4be3b55db81` FOREIGN KEY (`cancelled_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_44d36110fb38f45c2f15c946ddb` FOREIGN KEY (`driver_id`) REFERENCES `drivers` (`id`),
  CONSTRAINT `FK_ab4b806373c2ee43946679d572e` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicles` (`id`),
  CONSTRAINT `FK_e49dbbd9991c9b7baec9779e7ce` FOREIGN KEY (`route_id`) REFERENCES `routes` (`id`),
  CONSTRAINT `FK_ee38d00bcd1ef4a005bab44c0a4` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.user_roles definition

CREATE TABLE `user_roles` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `user_id` varchar(255) NOT NULL,
  `role_id` varchar(255) NOT NULL,
  `company_id` varchar(255) NOT NULL,
  `assigned_at` timestamp NOT NULL,
  `assigned_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_87b8888186ca9769c960e926870` (`user_id`),
  KEY `FK_b23c65e50a758245a33ee35fda1` (`role_id`),
  KEY `FK_df162a656b0dd26d4f1b76089ce` (`company_id`),
  KEY `FK_6de6fefffe4a6d17de747bf8b9d` (`assigned_by`),
  CONSTRAINT `FK_6de6fefffe4a6d17de747bf8b9d` FOREIGN KEY (`assigned_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_87b8888186ca9769c960e926870` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_b23c65e50a758245a33ee35fda1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`),
  CONSTRAINT `FK_df162a656b0dd26d4f1b76089ce` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.vehicle_inspections definition

CREATE TABLE `vehicle_inspections` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `vehicle_id` varchar(255) NOT NULL,
  `driver_id` varchar(255) NOT NULL,
  `inspection_date` date NOT NULL,
  `inspection_time` time NOT NULL,
  `checklist` json NOT NULL,
  `mileage` int NOT NULL,
  `fuel_level` varchar(50) NOT NULL,
  `overall_status` varchar(50) NOT NULL,
  `general_observations` text,
  `issues_found` text,
  `requires_maintenance` tinyint NOT NULL DEFAULT '0',
  `photos` json DEFAULT NULL,
  `driver_signature_url` text,
  `supervisor_signature_url` text,
  `approved_by` varchar(255) DEFAULT NULL,
  `approved_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_ab32303b0ae9f7a433ec4d17b42` (`vehicle_id`),
  KEY `FK_8ae6d76e4848053648116f38523` (`driver_id`),
  KEY `FK_ad07643e438aee85ac37a69a3b4` (`approved_by`),
  CONSTRAINT `FK_8ae6d76e4848053648116f38523` FOREIGN KEY (`driver_id`) REFERENCES `drivers` (`id`),
  CONSTRAINT `FK_ab32303b0ae9f7a433ec4d17b42` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicles` (`id`),
  CONSTRAINT `FK_ad07643e438aee85ac37a69a3b4` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.vehicle_maintenance definition

CREATE TABLE `vehicle_maintenance` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `vehicle_id` varchar(255) NOT NULL,
  `maintenance_type` varchar(100) NOT NULL,
  `service_type` varchar(100) NOT NULL,
  `service_date` date NOT NULL,
  `mileage_at_service` int NOT NULL,
  `service_provider` varchar(255) NOT NULL,
  `mechanic_name` varchar(255) DEFAULT NULL,
  `invoice_number` varchar(100) DEFAULT NULL,
  `labor_cost` decimal(10,2) DEFAULT NULL,
  `parts_cost` decimal(10,2) DEFAULT NULL,
  `total_cost` decimal(10,2) NOT NULL,
  `description` text NOT NULL,
  `parts_replaced` text,
  `next_service_date` date DEFAULT NULL,
  `next_service_mileage` int DEFAULT NULL,
  `invoices` json DEFAULT NULL,
  `photos` json DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'completed',
  `performed_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_c17c3f85165d93aab185c9c7aa8` (`vehicle_id`),
  KEY `FK_90e60992964d49c5f05b7f90631` (`performed_by`),
  CONSTRAINT `FK_90e60992964d49c5f05b7f90631` FOREIGN KEY (`performed_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_c17c3f85165d93aab185c9c7aa8` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicles` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.attendance definition

CREATE TABLE `attendance` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `company_id` varchar(255) NOT NULL,
  `student_id` varchar(255) NOT NULL,
  `level_id` varchar(255) NOT NULL,
  `date` date NOT NULL,
  `status` varchar(50) NOT NULL,
  `check_in_time` time DEFAULT NULL,
  `check_out_time` time DEFAULT NULL,
  `late_minutes` int DEFAULT NULL,
  `absence_reason` varchar(100) DEFAULT NULL,
  `observations` text,
  `justification_document_url` text,
  `recorded_by` varchar(255) NOT NULL,
  `last_modified_by` varchar(255) DEFAULT NULL,
  `can_edit_until` timestamp NOT NULL,
  `is_locked` tinyint NOT NULL DEFAULT '0',
  `locked_at` timestamp NULL DEFAULT NULL,
  `locked_by` varchar(255) DEFAULT NULL,
  `guardian_notified` tinyint NOT NULL DEFAULT '0',
  `guardian_notified_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_39644a1a10d75b6f2148eb891a5` (`company_id`),
  KEY `FK_6200532f3ef99f639a27bdcae7f` (`student_id`),
  KEY `FK_36777a1a265e42e66f71da389df` (`level_id`),
  KEY `FK_ecf22de8b4982cdf22feafb1800` (`recorded_by`),
  KEY `FK_17cae0e4ae332cf320453284bb9` (`last_modified_by`),
  KEY `FK_0cecf8f37283be50dfd9fc85cec` (`locked_by`),
  CONSTRAINT `FK_0cecf8f37283be50dfd9fc85cec` FOREIGN KEY (`locked_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_17cae0e4ae332cf320453284bb9` FOREIGN KEY (`last_modified_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_36777a1a265e42e66f71da389df` FOREIGN KEY (`level_id`) REFERENCES `levels` (`id`),
  CONSTRAINT `FK_39644a1a10d75b6f2148eb891a5` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `FK_6200532f3ef99f639a27bdcae7f` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `FK_ecf22de8b4982cdf22feafb1800` FOREIGN KEY (`recorded_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.attendance_alerts definition

CREATE TABLE `attendance_alerts` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `company_id` varchar(255) NOT NULL,
  `student_id` varchar(255) NOT NULL,
  `alert_type` varchar(50) NOT NULL,
  `total_absences` int NOT NULL,
  `consecutive_absences` int DEFAULT NULL,
  `total_lates` int DEFAULT NULL,
  `date_range_start` date NOT NULL,
  `date_range_end` date NOT NULL,
  `severity` varchar(50) NOT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'active',
  `guardian_contacted` tinyint NOT NULL DEFAULT '0',
  `guardian_contacted_at` timestamp NULL DEFAULT NULL,
  `guardian_contacted_by` varchar(255) DEFAULT NULL,
  `action_taken` text,
  `notes` text,
  `resolved_at` timestamp NULL DEFAULT NULL,
  `resolved_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_d873e12fb2392f654d49d7d53fe` (`company_id`),
  KEY `FK_6e06a76046743b01428f86498c1` (`student_id`),
  KEY `FK_9f9429860ec6de06e0ef84dcb68` (`guardian_contacted_by`),
  KEY `FK_0d9a24d19ecc19e9e581195870f` (`resolved_by`),
  CONSTRAINT `FK_0d9a24d19ecc19e9e581195870f` FOREIGN KEY (`resolved_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_6e06a76046743b01428f86498c1` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `FK_9f9429860ec6de06e0ef84dcb68` FOREIGN KEY (`guardian_contacted_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_d873e12fb2392f654d49d7d53fe` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.driver_documents definition

CREATE TABLE `driver_documents` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `driver_id` varchar(255) NOT NULL,
  `document_type` varchar(50) NOT NULL,
  `document_name` varchar(255) NOT NULL,
  `file_url` text NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `file_size` int NOT NULL,
  `mime_type` varchar(100) NOT NULL,
  `issue_date` date DEFAULT NULL,
  `expiry_date` date DEFAULT NULL,
  `is_permanent` tinyint NOT NULL DEFAULT '0',
  `status` varchar(50) NOT NULL DEFAULT 'valid',
  `verified` tinyint NOT NULL DEFAULT '0',
  `verified_by` varchar(255) DEFAULT NULL,
  `verified_at` timestamp NULL DEFAULT NULL,
  `verification_notes` text,
  `reminder_sent` tinyint NOT NULL DEFAULT '0',
  `reminder_sent_at` timestamp NULL DEFAULT NULL,
  `notes` text,
  `uploaded_by` varchar(255) NOT NULL,
  `uploaded_at` timestamp NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_dc156b37dfa0fcda0ef1974bab8` (`driver_id`),
  KEY `FK_c75253762e3956e2a685eea3c4f` (`verified_by`),
  KEY `FK_7df9ac5036fb9c0e660232be5a0` (`uploaded_by`),
  CONSTRAINT `FK_7df9ac5036fb9c0e660232be5a0` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_c75253762e3956e2a685eea3c4f` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_dc156b37dfa0fcda0ef1974bab8` FOREIGN KEY (`driver_id`) REFERENCES `drivers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.driver_vehicle_assignments definition

CREATE TABLE `driver_vehicle_assignments` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `driver_id` varchar(255) NOT NULL,
  `vehicle_id` varchar(255) NOT NULL,
  `assignment_date` date NOT NULL,
  `unassignment_date` date DEFAULT NULL,
  `is_primary_driver` tinyint NOT NULL DEFAULT '1',
  `assigned_by` varchar(255) NOT NULL,
  `unassigned_by` varchar(255) DEFAULT NULL,
  `unassignment_reason` text,
  `notes` text,
  PRIMARY KEY (`id`),
  KEY `FK_0b484816a9e7637fe82772a51e6` (`driver_id`),
  KEY `FK_6648d9f31074452d7b8b52dd4af` (`vehicle_id`),
  KEY `FK_3648e53c293cd7c3e758be43b41` (`assigned_by`),
  KEY `FK_961ecb2b6eb8a0a44fc23c263cc` (`unassigned_by`),
  CONSTRAINT `FK_0b484816a9e7637fe82772a51e6` FOREIGN KEY (`driver_id`) REFERENCES `drivers` (`id`),
  CONSTRAINT `FK_3648e53c293cd7c3e758be43b41` FOREIGN KEY (`assigned_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_6648d9f31074452d7b8b52dd4af` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicles` (`id`),
  CONSTRAINT `FK_961ecb2b6eb8a0a44fc23c263cc` FOREIGN KEY (`unassigned_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.emergency_contacts definition

CREATE TABLE `emergency_contacts` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `student_id` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `relationship` varchar(100) NOT NULL,
  `phone` varchar(50) NOT NULL,
  `phone_secondary` varchar(50) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `address` text,
  `priority` int NOT NULL DEFAULT '1',
  `notes` text,
  `is_active` tinyint NOT NULL DEFAULT '1',
  `created_by` varchar(255) DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_f12b6969989d6092bd7c20a9884` (`student_id`),
  KEY `FK_73395820a5ea9e12959da66b02b` (`created_by`),
  KEY `FK_631176f49ea836260707c73a59f` (`updated_by`),
  CONSTRAINT `FK_631176f49ea836260707c73a59f` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_73395820a5ea9e12959da66b02b` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_f12b6969989d6092bd7c20a9884` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.invitations definition

CREATE TABLE `invitations` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `firstName` varchar(255) NOT NULL,
  `lastName` varchar(255) NOT NULL,
  `student_id` varchar(255) NOT NULL,
  `company_id` varchar(255) NOT NULL,
  `role_id` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `expiresAt` timestamp NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `invited_by` varchar(255) NOT NULL,
  `invitedAt` timestamp NOT NULL,
  `acceptedAt` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_e577dcf9bb6d084373ed399850` (`token`),
  KEY `FK_8e44a266f25a1bbdbea17413220` (`student_id`),
  KEY `FK_53407578b13649da4cac07455ad` (`company_id`),
  KEY `FK_e4950c4d6aa2236f5213538e01a` (`role_id`),
  KEY `FK_29b1cef6891d9b9d4e35f793b81` (`invited_by`),
  CONSTRAINT `FK_29b1cef6891d9b9d4e35f793b81` FOREIGN KEY (`invited_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_53407578b13649da4cac07455ad` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `FK_8e44a266f25a1bbdbea17413220` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `FK_e4950c4d6aa2236f5213538e01a` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.medical_incidents definition

CREATE TABLE `medical_incidents` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `company_id` varchar(255) NOT NULL,
  `student_id` varchar(255) NOT NULL,
  `incident_type` varchar(100) NOT NULL,
  `severity` varchar(50) NOT NULL,
  `incident_date` timestamp NOT NULL,
  `location` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `symptoms` text,
  `temperature` decimal(4,2) DEFAULT NULL,
  `actions_taken` text NOT NULL,
  `medication_given` varchar(255) DEFAULT NULL,
  `medication_dosage` varchar(100) DEFAULT NULL,
  `medication_time` timestamp NULL DEFAULT NULL,
  `guardian_notified` tinyint NOT NULL DEFAULT '0',
  `guardian_notified_at` timestamp NULL DEFAULT NULL,
  `guardian_notified_by` varchar(255) DEFAULT NULL,
  `guardian_id` varchar(255) DEFAULT NULL,
  `required_medical_attention` tinyint NOT NULL DEFAULT '0',
  `medical_center_visited` varchar(255) DEFAULT NULL,
  `doctor_seen` varchar(255) DEFAULT NULL,
  `diagnosis` text,
  `treatment_received` text,
  `follow_up_required` tinyint NOT NULL DEFAULT '0',
  `follow_up_notes` text,
  `follow_up_date` date DEFAULT NULL,
  `resolved_at` timestamp NULL DEFAULT NULL,
  `reported_by` varchar(255) NOT NULL,
  `witnessed_by` text,
  `photos` json DEFAULT NULL,
  `documents` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_c1d56840b0ff3c4ff795437a899` (`company_id`),
  KEY `FK_523203df536264e86d0068a5efb` (`student_id`),
  KEY `FK_be8a941fa4561f77ffc0ebdd0fc` (`guardian_notified_by`),
  KEY `FK_f70bf50d7af56345e45f3be781f` (`guardian_id`),
  KEY `FK_4897c24ac94a2a3a4e914a4a8c5` (`reported_by`),
  CONSTRAINT `FK_4897c24ac94a2a3a4e914a4a8c5` FOREIGN KEY (`reported_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_523203df536264e86d0068a5efb` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `FK_be8a941fa4561f77ffc0ebdd0fc` FOREIGN KEY (`guardian_notified_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_c1d56840b0ff3c4ff795437a899` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `FK_f70bf50d7af56345e45f3be781f` FOREIGN KEY (`guardian_id`) REFERENCES `guardians` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.medical_info definition

CREATE TABLE `medical_info` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `student_id` varchar(255) NOT NULL,
  `blood_type` varchar(10) DEFAULT NULL,
  `blood_type_verified` tinyint NOT NULL DEFAULT '0',
  `has_allergies` tinyint NOT NULL DEFAULT '0',
  `allergies` text,
  `allergy_severity` varchar(50) DEFAULT NULL,
  `has_dietary_restrictions` tinyint NOT NULL DEFAULT '0',
  `dietary_restrictions` text,
  `dietary_restriction_type` varchar(100) DEFAULT NULL,
  `takes_regular_medication` tinyint NOT NULL DEFAULT '0',
  `medications` text,
  `medication_schedule` text,
  `medication_administration_notes` text,
  `has_chronic_conditions` tinyint NOT NULL DEFAULT '0',
  `chronic_conditions` text,
  `has_asthma` tinyint NOT NULL DEFAULT '0',
  `has_diabetes` tinyint NOT NULL DEFAULT '0',
  `has_epilepsy` tinyint NOT NULL DEFAULT '0',
  `has_autism` tinyint NOT NULL DEFAULT '0',
  `has_adhd` tinyint NOT NULL DEFAULT '0',
  `health_insurance_provider` varchar(100) DEFAULT NULL,
  `health_insurance_type` varchar(50) DEFAULT NULL,
  `health_insurance_number` varchar(100) DEFAULT NULL,
  `doctor_name` varchar(255) DEFAULT NULL,
  `doctor_specialty` varchar(100) DEFAULT NULL,
  `doctor_phone` varchar(50) DEFAULT NULL,
  `doctor_email` varchar(255) DEFAULT NULL,
  `preferred_hospital` varchar(255) DEFAULT NULL,
  `preferred_hospital_address` text,
  `preferred_hospital_phone` varchar(50) DEFAULT NULL,
  `has_special_needs` tinyint NOT NULL DEFAULT '0',
  `special_needs_type` varchar(100) DEFAULT NULL,
  `special_needs_description` text,
  `requires_special_equipment` tinyint NOT NULL DEFAULT '0',
  `special_equipment_description` text,
  `vaccination_card_url` text,
  `vaccination_up_to_date` tinyint DEFAULT NULL,
  `vaccination_notes` text,
  `general_observations` text,
  `has_activity_restrictions` tinyint NOT NULL DEFAULT '0',
  `activity_restrictions` text,
  `consent_emergency_treatment` tinyint NOT NULL DEFAULT '1',
  `consent_medication_administration` tinyint NOT NULL DEFAULT '0',
  `consent_given_by` varchar(255) DEFAULT NULL,
  `consent_date` timestamp NULL DEFAULT NULL,
  `last_updated_by` varchar(255) DEFAULT NULL,
  `last_reviewed_date` date DEFAULT NULL,
  `next_review_date` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `REL_12dfac6d02d8176c571548ee3d` (`student_id`),
  KEY `FK_ab800dcda16c80b35d22aa2cb25` (`consent_given_by`),
  KEY `FK_4c4bdda3714069a1253bfe5fd54` (`last_updated_by`),
  CONSTRAINT `FK_12dfac6d02d8176c571548ee3d7` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `FK_4c4bdda3714069a1253bfe5fd54` FOREIGN KEY (`last_updated_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_ab800dcda16c80b35d22aa2cb25` FOREIGN KEY (`consent_given_by`) REFERENCES `guardians` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.route_stops definition

CREATE TABLE `route_stops` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `route_id` varchar(255) NOT NULL,
  `student_id` varchar(255) NOT NULL,
  `stop_order` int NOT NULL,
  `stop_name` varchar(255) DEFAULT NULL,
  `address` text NOT NULL,
  `address_reference` text,
  `latitude` decimal(10,8) NOT NULL,
  `longitude` decimal(11,8) NOT NULL,
  `location_accuracy_meters` int DEFAULT NULL,
  `stop_type` varchar(50) NOT NULL DEFAULT 'regular',
  `authorized_guardians` json NOT NULL,
  `estimated_time_from_start_minutes` int NOT NULL,
  `estimated_arrival_time` time DEFAULT NULL,
  `typical_wait_time_minutes` int NOT NULL DEFAULT '2',
  `pickup_instructions` text,
  `special_requirements` text,
  `contact_phone` varchar(50) DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `notes` text,
  `is_temporary` tinyint NOT NULL DEFAULT '0',
  `is_active` tinyint NOT NULL DEFAULT '1',
  `valid_until` date DEFAULT NULL,
  `valid_from` date DEFAULT NULL,
  `operating_days` json DEFAULT NULL,
  `applies_sunday` tinyint NOT NULL DEFAULT '0',
  `applies_saturday` tinyint NOT NULL DEFAULT '0',
  `applies_friday` tinyint NOT NULL DEFAULT '1',
  `applies_thursday` tinyint NOT NULL DEFAULT '1',
  `applies_wednesday` tinyint NOT NULL DEFAULT '1',
  `applies_tuesday` tinyint NOT NULL DEFAULT '1',
  `applies_monday` tinyint NOT NULL DEFAULT '1',
  `geofence_radius_meters` int NOT NULL DEFAULT '100',
  `alternative_contact_phone` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_b16cab5c66870949cbb4ee748c0` (`route_id`),
  KEY `FK_1607938363b9a1db60e391c9805` (`student_id`),
  KEY `FK_ba57d7af70642ca0115492e4cc9` (`created_by`),
  CONSTRAINT `FK_1607938363b9a1db60e391c9805` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `FK_b16cab5c66870949cbb4ee748c0` FOREIGN KEY (`route_id`) REFERENCES `routes` (`id`),
  CONSTRAINT `FK_ba57d7af70642ca0115492e4cc9` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.student_guardians definition

CREATE TABLE `student_guardians` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `student_id` varchar(255) NOT NULL,
  `guardian_id` varchar(255) NOT NULL,
  `relationship_type` varchar(100) NOT NULL,
  `priority` int NOT NULL DEFAULT '1',
  `can_pickup` tinyint NOT NULL DEFAULT '1',
  `can_receive_communications` tinyint NOT NULL DEFAULT '1',
  `can_authorize_medical` tinyint NOT NULL DEFAULT '0',
  `can_see_academic_info` tinyint NOT NULL DEFAULT '1',
  `has_legal_custody` tinyint NOT NULL DEFAULT '1',
  `custody_type` varchar(50) DEFAULT NULL,
  `custody_notes` text,
  `lives_with_student` tinyint NOT NULL DEFAULT '1',
  `is_active` tinyint NOT NULL DEFAULT '1',
  `created_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_8194052bdd62204f061dd44e0c9` (`student_id`),
  KEY `FK_ec3cd56a2093be19f778af57c63` (`guardian_id`),
  KEY `FK_10c67f3642a828cb55db78873a4` (`created_by`),
  CONSTRAINT `FK_10c67f3642a828cb55db78873a4` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_8194052bdd62204f061dd44e0c9` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `FK_ec3cd56a2093be19f778af57c63` FOREIGN KEY (`guardian_id`) REFERENCES `guardians` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.student_observations definition

CREATE TABLE `student_observations` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `class_book_entry_id` varchar(255) NOT NULL,
  `student_id` varchar(255) NOT NULL,
  `observation` text NOT NULL,
  `category` varchar(50) NOT NULL,
  `development_area` varchar(100) DEFAULT NULL,
  `core_learning` varchar(100) DEFAULT NULL,
  `is_positive` tinyint NOT NULL DEFAULT '1',
  `achievement_level` varchar(50) DEFAULT NULL,
  `suggested_actions` text,
  `requires_follow_up` tinyint NOT NULL DEFAULT '0',
  `follow_up_date` date DEFAULT NULL,
  `is_shared_with_guardian` tinyint NOT NULL DEFAULT '0',
  `shared_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_a36a16bf0ca646590427e012dc3` (`class_book_entry_id`),
  KEY `FK_5c5a539e21a7e5d5a5f47ff8a7b` (`student_id`),
  CONSTRAINT `FK_5c5a539e21a7e5d5a5f47ff8a7b` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `FK_a36a16bf0ca646590427e012dc3` FOREIGN KEY (`class_book_entry_id`) REFERENCES `class_book_entries` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.trip_incidents definition

CREATE TABLE `trip_incidents` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `trip_id` varchar(255) NOT NULL,
  `company_id` varchar(255) NOT NULL,
  `incident_type` varchar(100) NOT NULL,
  `incident_category` varchar(50) NOT NULL,
  `severity` varchar(50) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `latitude` decimal(10,8) NOT NULL,
  `longitude` decimal(11,8) NOT NULL,
  `location_description` text,
  `occurred_at` timestamp NOT NULL,
  `reported_at` timestamp NOT NULL,
  `resolved_at` timestamp NULL DEFAULT NULL,
  `resolution_time_minutes` int DEFAULT NULL,
  `reported_by_driver` tinyint NOT NULL DEFAULT '1',
  `students_involved` json DEFAULT NULL,
  `caused_delay` tinyint NOT NULL DEFAULT '0',
  `delay_minutes` int DEFAULT NULL,
  `required_route_change` tinyint NOT NULL DEFAULT '0',
  `required_assistance` tinyint NOT NULL DEFAULT '0',
  `assistance_type` varchar(100) DEFAULT NULL,
  `assistance_called_at` timestamp NULL DEFAULT NULL,
  `assistance_arrived_at` timestamp NULL DEFAULT NULL,
  `police_notified` tinyint NOT NULL DEFAULT '0',
  `police_report_number` varchar(100) DEFAULT NULL,
  `ambulance_called` tinyint NOT NULL DEFAULT '0',
  `guardians_notified` tinyint NOT NULL DEFAULT '0',
  `guardians_notified_at` timestamp NULL DEFAULT NULL,
  `company_notified` tinyint NOT NULL DEFAULT '0',
  `company_notified_at` timestamp NULL DEFAULT NULL,
  `notification_message` text,
  `actions_taken` text NOT NULL,
  `estimated_cost` decimal(10,2) DEFAULT NULL,
  `actual_cost` decimal(10,2) DEFAULT NULL,
  `photos` json DEFAULT NULL,
  `videos` json DEFAULT NULL,
  `documents` json DEFAULT NULL,
  `requires_follow_up` tinyint NOT NULL DEFAULT '0',
  `follow_up_action` text,
  `follow_up_responsible` varchar(255) DEFAULT NULL,
  `follow_up_deadline` date DEFAULT NULL,
  `follow_up_completed` tinyint NOT NULL DEFAULT '0',
  `follow_up_completed_at` timestamp NULL DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'open',
  `preventable` tinyint DEFAULT NULL,
  `prevention_measures` text,
  PRIMARY KEY (`id`),
  KEY `FK_dea33fca4e7b4cc78d97f545d31` (`trip_id`),
  KEY `FK_dc2120375787248bbaff23c9249` (`company_id`),
  KEY `FK_5b1ceed59c76c5fcb3603f5e011` (`follow_up_responsible`),
  CONSTRAINT `FK_5b1ceed59c76c5fcb3603f5e011` FOREIGN KEY (`follow_up_responsible`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_dc2120375787248bbaff23c9249` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `FK_dea33fca4e7b4cc78d97f545d31` FOREIGN KEY (`trip_id`) REFERENCES `trips` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.trip_stops definition

CREATE TABLE `trip_stops` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `trip_id` varchar(255) NOT NULL,
  `route_stop_id` varchar(255) NOT NULL,
  `student_id` varchar(255) NOT NULL,
  `planned_order` int NOT NULL,
  `actual_order` float DEFAULT NULL,
  `estimated_arrival_time` time NOT NULL,
  `actual_arrival_time` time DEFAULT NULL,
  `actual_departure_time` time DEFAULT NULL,
  `wait_time_minutes` int DEFAULT NULL,
  `actual_latitude` decimal(10,8) DEFAULT NULL,
  `actual_longitude` decimal(11,8) DEFAULT NULL,
  `distance_from_planned_meters` int DEFAULT NULL,
  `status` varchar(50) NOT NULL,
  `student_action` varchar(50) DEFAULT NULL,
  `guardian_present_id` varchar(255) DEFAULT NULL,
  `guardian_present_name` varchar(255) DEFAULT NULL,
  `id_verified` tinyint NOT NULL DEFAULT '0',
  `action_timestamp` timestamp NULL DEFAULT NULL,
  `skip_reason` varchar(100) DEFAULT NULL,
  `skip_details` text,
  `approach_notification_sent` tinyint NOT NULL DEFAULT '0',
  `approach_notification_sent_at` timestamp NULL DEFAULT NULL,
  `arrival_notification_sent` tinyint NOT NULL DEFAULT '0',
  `arrival_notification_sent_at` timestamp NULL DEFAULT NULL,
  `notes` text,
  PRIMARY KEY (`id`),
  KEY `FK_5cb5ec6432abdf6f1e1c3a0970c` (`trip_id`),
  KEY `FK_46f6050e11ebeda000a48ee7501` (`route_stop_id`),
  KEY `FK_56d25f3d7b41fed907ce29ce309` (`student_id`),
  KEY `FK_59959aeea7b7d6fc20b4f850364` (`guardian_present_id`),
  CONSTRAINT `FK_46f6050e11ebeda000a48ee7501` FOREIGN KEY (`route_stop_id`) REFERENCES `route_stops` (`id`),
  CONSTRAINT `FK_56d25f3d7b41fed907ce29ce309` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `FK_59959aeea7b7d6fc20b4f850364` FOREIGN KEY (`guardian_present_id`) REFERENCES `guardians` (`id`),
  CONSTRAINT `FK_5cb5ec6432abdf6f1e1c3a0970c` FOREIGN KEY (`trip_id`) REFERENCES `trips` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- saas_jardines_dev.driver_document_alerts definition

CREATE TABLE `driver_document_alerts` (
  `id` varchar(36) NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `company_id` varchar(255) NOT NULL,
  `driver_id` varchar(255) NOT NULL,
  `document_id` varchar(255) NOT NULL,
  `alert_type` varchar(50) NOT NULL,
  `severity` varchar(50) NOT NULL,
  `message` text NOT NULL,
  `days_until_expiry` int DEFAULT NULL,
  `is_active` tinyint NOT NULL DEFAULT '1',
  `acknowledged` tinyint NOT NULL DEFAULT '0',
  `acknowledged_by` varchar(255) DEFAULT NULL,
  `acknowledged_at` timestamp NULL DEFAULT NULL,
  `resolved` tinyint NOT NULL DEFAULT '0',
  `resolved_at` timestamp NULL DEFAULT NULL,
  `resolved_by` varchar(255) DEFAULT NULL,
  `resolution_notes` text,
  PRIMARY KEY (`id`),
  KEY `FK_c3beb3a47105a3557b1e70bff38` (`company_id`),
  KEY `FK_39e4f03210d0d5b1071e5262f13` (`driver_id`),
  KEY `FK_dca1a1f65c23697d896768e8949` (`document_id`),
  KEY `FK_957a5e3b6cdf333369bf5c356a3` (`acknowledged_by`),
  KEY `FK_85ffe3d49d5b4a9b51a1a21e903` (`resolved_by`),
  CONSTRAINT `FK_39e4f03210d0d5b1071e5262f13` FOREIGN KEY (`driver_id`) REFERENCES `drivers` (`id`),
  CONSTRAINT `FK_85ffe3d49d5b4a9b51a1a21e903` FOREIGN KEY (`resolved_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_957a5e3b6cdf333369bf5c356a3` FOREIGN KEY (`acknowledged_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FK_c3beb3a47105a3557b1e70bff38` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
  CONSTRAINT `FK_dca1a1f65c23697d896768e8949` FOREIGN KEY (`document_id`) REFERENCES `driver_documents` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;